inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140

Layout/IndentationConsistency:
  EnforcedStyle: rails
