inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  TargetRubyVersion: 2.2.1

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140

Layout/IndentationConsistency:
  EnforcedStyle: rails

# Style/EmptyMethod:
#   Enabled: false

# Style/StringLiterals:
#   Enabled: false

# Style/SymbolProc:
#   Enabled: false

# Style/FrozenStringLiteralComment:
#   Enabled: false

# Style/PercentLiteralDelimiters:
#   Enabled: false

# Style/SymbolArray:
#   Enabled: false

# Layout/EmptyLinesAroundClassBody:
#   Enabled: false

# Layout/EmptyLinesAroundBlockBody:
#   Enabled: false

# Layout/EmptyLinesAroundModuleBody:
#   Enabled: false

# Layout/SpaceBeforeBlockBraces:
#   Enabled: false

# Layout/SpaceInsideBrackets:
#   Enabled: false

# Layout/SpaceInsideHashLiteralBraces:
#   Enabled: false

# Layout/SpaceInsideBlockBraces:
#   Enabled: false

# Layout/TrailingBlankLines:
#   Enabled: false

# Rails/ApplicationRecord:
#   Enabled: false
