production:
  solr:
    hostname: rorsearchpro03a.munimadrid.es
    port: 8080
    log_level: WARNING
    path: /solr-agendas

preproduction:
  solr:
    hostname: rorsearchpre03a.munimadrid.es
    port: 8080
    log_level: WARNING
    path: /solr-agendas

staging:
  solr:
    hostname: rorappdesa03a.munimadrid.es
    port: 8080
    log_level: INFO
    path: /solr-agendas

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/test

